config:
  yaml:
log:
  disable_sentry: true

listener:
  addr: :7899

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: doorman
  service_port: 80

vault:
  endpoint: ""
  token: ""
  mount_path: ""
  secret_path: ""
  private_key_path: ""
  address_registry: ""


eth_rpc:
  endpoint: ""

service:
  token_expire_time: 1h
  token_key:  ""
  refresh_token_expire_time: 8h