config:
  yaml:
log:
  disable_sentry: true

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: doorman
  service_port: 80

vault:
  endpoint: ""
  
service:
  token_expire_time: 1h or other value, see time.ParseDuration
  token_key:  "something sha256'd, has to be a 64 char long hex string"
  refresh_token_expire_time: 8hor other value, see time.ParseDuration