config:
  yaml:
log:
  disable_sentry: true

listener:
  addr: :7899

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: doorman
  service_port: 80

vault:
  endpoint: ""

eth_rpc:
  endpoint: "http://localhost:8543"

service:
  token_expire_time: 1h
  token_key:  "0xa781b36ba9b393e67b0b50d6255637f28353409d8e390645beb408cc64b108db"
  refresh_token_expire_time: 8h