config:
  yaml:
log:
  disable_sentry: true

listener:
  addr: :7899

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: doorman
  service_port: 80

vault:
  endpoint: "http://143.244.197.187:8200"
  token: "hvs.H3l9B1yFUfewDGxMgl7WO60O"
  mount_path: "/core/"
  private_key_path: "ea15fcfd7ea1b2d04042341e7463a3b7fceab157a923b7a8ad3ea12242a4cf0e"
  address_registry: "0x02f35683c4834A389c1B7EA8a8b1Da4d4dD940bF"


eth_rpc:
  endpoint: "http://localhost:8543"

service:
  token_expire_time: 1h
  token_key:  "0xa781b36ba9b393e67b0b50d6255637f28353409d8e390645beb408cc64b108db"
  refresh_token_expire_time: 8hd